name: darkstuff productions
favicon: null
layout_spectrum: 0.8537645637989044
typography_spectrum: 0.39119328022934496
title: darkstuff productions
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FE1212'
    - '#17273B'
    - '#2850FF'
    - '#FCD906'
    - '#4D565A'
  brandStrength: 0.3829305307008326
  lightness: 0.14282172033563256
  saturation: 0.9156843179371208
  rhythmicContrast: 0.7484537472482771
purpose: []
