typography_spectrum: 0.6115970285609365
color:
  brandColors:
    - '#FE1212'
    - '#17273B'
    - '#2850FF'
    - '#FCD906'
    - '#4D565A'
  brandStrength: 0.9899625447578728
  lightness: 0.14195154351182282
  saturation: 0.401080846786499
  rhythmicContrast: 0.4622365962713957
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24319378309883177
analytics:
  google: null
  facebook: null
  twitter: null
name: darkstuff productions
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: darkstuff productions
purpose: []
