typography_spectrum: 0.020724802976474166
color:
  brandColors:
    - '#FE1212'
    - '#17273B'
    - '#2850FF'
    - '#FCD906'
    - '#4D565A'
  brandStrength: 0.6899268561974168
  lightness: 0.37413408677093685
  saturation: 0.758195836097002
  rhythmicContrast: 0.3402097304351628
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29967917152680457
analytics:
  google: null
  facebook: null
  twitter: null
name: darkstuff productions
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ' PICTURES'
    id: 84f2560b-1588-42c6-8e47-c2fdfeb66534
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: darkstuff productions
purpose: []
