typography_spectrum: 0.5003774783108383
color:
  brandColors:
    - '#B4AF91'
    - '#787746'
    - '#40411E'
    - '#32331D'
    - '#C03000'
  brandStrength: 0.709332553204149
  lightness: 0.17849278636276722
  saturation: 0.22662052139639854
  rhythmicContrast: 0.7963357265107334
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3872740650549531
analytics:
  google: null
  facebook: null
  twitter: null
name: darkstuff productions
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: darkstuff productions
purpose: []
